### ISSUE TITLE
Comments are not displayed and the edit button is missing

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/comment#2]
I may have spotted a small bug in MR 5.6 - the comments are not displayed and the edit button is missing. Error:
`PHP Warning:  The use statement with non-compound name 'Parsedown' has no effect in /vendor/munkireport/comment/comment_controller.php on line 3`

<img width="408" alt="image" src="https://user-images.githubusercontent.com/16665880/105560390-8443ee80-5d0b-11eb-9e2b-b43c4c29f4af.png">

vs

<img width="472" alt="image" src="https://user-images.githubusercontent.com/16665880/105560404-8c9c2980-5d0b-11eb-80bc-bec87f171cbd.png">

**Comment by ofirgalcon** [comment]
I found a fix - removed `use \Parsedown;` from comment_controller.php

**Comment by ofirgalcon** [comment]
Another fix https://github.com/munkireport/comment/pull/1/commits/336830f4e4ae2a4dd719af7fed051b49091af9f5

**Comment by tuxudo** [comment]
Resolved with v4.1 of the module
